# Generated by Django 3.0.5 on 2020-07-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lead_content', models.CharField(max_length=300)),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('them_images', models.URLField()),
                ('body_title', models.CharField(max_length=200)),
                ('summay', models.CharField(max_length=300)),
                ('links', models.URLField()),
            ],
        ),
    ]
