# Generated by Django 3.0.5 on 2020-07-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200714_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainnews',
            name='image_caption',
            field=models.CharField(default='', max_length=30000),
        ),
    ]
