# Generated by Django 3.0.5 on 2020-07-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mainnews_image_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(default='', max_length=300000)),
            ],
        ),
    ]
