# Generated by Django 3.0.5 on 2020-07-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_readnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='readnews',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='readnews',
            name='news',
            field=models.CharField(max_length=300000),
        ),
    ]
